create type "public"."Point Scales" as enum ('[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]');

drop policy "Enable insert for users based on user_id" on "public"."estimations";

drop policy "Enable insert for authenticated users only" on "public"."user_roles";

drop policy "Enable read access for all users" on "public"."user_roles";

revoke delete on table "public"."user_roles" from "anon";

revoke insert on table "public"."user_roles" from "anon";

revoke references on table "public"."user_roles" from "anon";

revoke select on table "public"."user_roles" from "anon";

revoke trigger on table "public"."user_roles" from "anon";

revoke truncate on table "public"."user_roles" from "anon";

revoke update on table "public"."user_roles" from "anon";

revoke delete on table "public"."user_roles" from "authenticated";

revoke insert on table "public"."user_roles" from "authenticated";

revoke references on table "public"."user_roles" from "authenticated";

revoke select on table "public"."user_roles" from "authenticated";

revoke trigger on table "public"."user_roles" from "authenticated";

revoke truncate on table "public"."user_roles" from "authenticated";

revoke update on table "public"."user_roles" from "authenticated";

revoke delete on table "public"."user_roles" from "service_role";

revoke insert on table "public"."user_roles" from "service_role";

revoke references on table "public"."user_roles" from "service_role";

revoke select on table "public"."user_roles" from "service_role";

revoke trigger on table "public"."user_roles" from "service_role";

revoke truncate on table "public"."user_roles" from "service_role";

revoke update on table "public"."user_roles" from "service_role";

revoke delete on table "public"."user_teams" from "anon";

revoke insert on table "public"."user_teams" from "anon";

revoke references on table "public"."user_teams" from "anon";

revoke select on table "public"."user_teams" from "anon";

revoke trigger on table "public"."user_teams" from "anon";

revoke truncate on table "public"."user_teams" from "anon";

revoke update on table "public"."user_teams" from "anon";

revoke delete on table "public"."user_teams" from "authenticated";

revoke insert on table "public"."user_teams" from "authenticated";

revoke references on table "public"."user_teams" from "authenticated";

revoke select on table "public"."user_teams" from "authenticated";

revoke trigger on table "public"."user_teams" from "authenticated";

revoke truncate on table "public"."user_teams" from "authenticated";

revoke update on table "public"."user_teams" from "authenticated";

revoke delete on table "public"."user_teams" from "service_role";

revoke insert on table "public"."user_teams" from "service_role";

revoke references on table "public"."user_teams" from "service_role";

revoke select on table "public"."user_teams" from "service_role";

revoke trigger on table "public"."user_teams" from "service_role";

revoke truncate on table "public"."user_teams" from "service_role";

revoke update on table "public"."user_teams" from "service_role";

alter table "public"."estimations" drop constraint "estimations_id_key";

alter table "public"."profiles" drop constraint "profiles_username_key";

alter table "public"."profiles" drop constraint "username_length";

alter table "public"."user_roles" drop constraint "user_roles_role_id_fkey";

alter table "public"."user_roles" drop constraint "user_roles_user_id_fkey";

alter table "public"."user_roles" drop constraint "user_roles_uuid_key";

alter table "public"."user_teams" drop constraint "user_teams_id_key";

alter table "public"."user_teams" drop constraint "user_teams_team_id_fkey";

alter table "public"."user_teams" drop constraint "user_teams_user_id_fkey";

alter table "public"."user_teams" drop constraint "user_teams_uuid_key";

alter table "public"."user_roles" drop constraint "user_roles_pkey";

alter table "public"."user_teams" drop constraint "user_teams_pkey";

alter table "public"."estimations" drop constraint "estimations_pkey";

drop index if exists "public"."estimations_id_key";

drop index if exists "public"."profiles_username_key";

drop index if exists "public"."user_roles_pkey";

drop index if exists "public"."user_teams_id_key";

drop index if exists "public"."user_teams_pkey";

drop index if exists "public"."user_teams_uuid_key";

drop index if exists "public"."estimations_pkey";

drop index if exists "public"."user_roles_uuid_key";

drop table "public"."user_roles";

drop table "public"."user_teams";

create table "public"."point_scales" (
    "id" bigint generated by default as identity not null,
    "uuid" uuid not null default gen_random_uuid(),
    "name" character varying,
    "scale" character varying,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."point_scales" enable row level security;

create table "public"."settings" (
    "id" bigint generated by default as identity not null,
    "uuid" uuid not null default gen_random_uuid(),
    "team_id" uuid,
    "require_review" boolean not null default true,
    "sc_api_key" text,
    "sc_label_id" smallint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "point_scale_id" uuid
);


create table "public"."users_roles" (
    "id" bigint generated by default as identity not null,
    "uuid" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "role_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."users_roles" enable row level security;

create table "public"."users_teams" (
    "user_id" uuid not null,
    "team_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."users_teams" enable row level security;

alter table "public"."epics" drop column "completed_estimation_at";

alter table "public"."epics" add column "story_count" smallint;

alter table "public"."epics" add column "team_completed_estimation_at" timestamp with time zone;

alter table "public"."epics" alter column "team_id" set not null;

alter table "public"."epics" disable row level security;

alter table "public"."estimations" add column "epic_id" uuid not null;

alter table "public"."estimations" add column "team_id" uuid not null;

alter table "public"."estimations" alter column "estimation" set not null;

alter table "public"."estimations" alter column "estimation_submitted" set not null;

alter table "public"."profiles" drop column "username";

alter table "public"."profiles" drop column "website";

alter table "public"."profiles" add column "created_at" timestamp with time zone;

alter table "public"."profiles" add column "email" text not null;

alter table "public"."stories" alter column "epic_id" set not null;

alter table "public"."stories" disable row level security;

alter table "public"."teams" add column "member_count" smallint;

CREATE UNIQUE INDEX point_scales_pkey ON public.point_scales USING btree (id);

CREATE UNIQUE INDEX point_scales_uuid_key ON public.point_scales USING btree (uuid);

CREATE UNIQUE INDEX settings_pkey ON public.settings USING btree (id);

CREATE UNIQUE INDEX users_roles_pkey ON public.users_roles USING btree (user_id, role_id);

CREATE UNIQUE INDEX users_teams_pkey ON public.users_teams USING btree (user_id, team_id);

CREATE UNIQUE INDEX estimations_pkey ON public.estimations USING btree (user_id, story_id);

CREATE UNIQUE INDEX user_roles_uuid_key ON public.users_roles USING btree (uuid);

alter table "public"."point_scales" add constraint "point_scales_pkey" PRIMARY KEY using index "point_scales_pkey";

alter table "public"."settings" add constraint "settings_pkey" PRIMARY KEY using index "settings_pkey";

alter table "public"."users_roles" add constraint "users_roles_pkey" PRIMARY KEY using index "users_roles_pkey";

alter table "public"."users_teams" add constraint "users_teams_pkey" PRIMARY KEY using index "users_teams_pkey";

alter table "public"."estimations" add constraint "estimations_pkey" PRIMARY KEY using index "estimations_pkey";

alter table "public"."estimations" add constraint "estimations_epic_id_fkey" FOREIGN KEY (epic_id) REFERENCES epics(uuid) not valid;

alter table "public"."estimations" validate constraint "estimations_epic_id_fkey";

alter table "public"."estimations" add constraint "estimations_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(uuid) not valid;

alter table "public"."estimations" validate constraint "estimations_team_id_fkey";

alter table "public"."point_scales" add constraint "point_scales_uuid_key" UNIQUE using index "point_scales_uuid_key";

alter table "public"."settings" add constraint "settings_point_scale_id_fkey" FOREIGN KEY (point_scale_id) REFERENCES point_scales(uuid) not valid;

alter table "public"."settings" validate constraint "settings_point_scale_id_fkey";

alter table "public"."settings" add constraint "settings_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(uuid) not valid;

alter table "public"."settings" validate constraint "settings_team_id_fkey";

alter table "public"."users_roles" add constraint "user_roles_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(uuid) not valid;

alter table "public"."users_roles" validate constraint "user_roles_role_id_fkey";

alter table "public"."users_roles" add constraint "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) not valid;

alter table "public"."users_roles" validate constraint "user_roles_user_id_fkey";

alter table "public"."users_roles" add constraint "user_roles_uuid_key" UNIQUE using index "user_roles_uuid_key";

alter table "public"."users_teams" add constraint "users_teams_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(uuid) not valid;

alter table "public"."users_teams" validate constraint "users_teams_team_id_fkey";

alter table "public"."users_teams" add constraint "users_teams_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) not valid;

alter table "public"."users_teams" validate constraint "users_teams_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.update_member_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Update the member count for the team being modified
    UPDATE public.teams
    SET member_count = (SELECT COUNT(*) FROM public.users_teams WHERE team_id = NEW.team_id)
    WHERE uuid = NEW.team_id;

    -- If the user is moving teams, update the previous team's member count
    IF TG_OP = 'UPDATE' THEN
        UPDATE public.teams
        SET member_count = (SELECT COUNT(*) FROM public.users_teams WHERE team_id = OLD.team_id)
        WHERE uuid = OLD.team_id;
    END IF;

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, email, created_at, updated_at)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.email, NOW(), NOW());
  
  RETURN new;
END;$function$
;

grant delete on table "public"."point_scales" to "anon";

grant insert on table "public"."point_scales" to "anon";

grant references on table "public"."point_scales" to "anon";

grant select on table "public"."point_scales" to "anon";

grant trigger on table "public"."point_scales" to "anon";

grant truncate on table "public"."point_scales" to "anon";

grant update on table "public"."point_scales" to "anon";

grant delete on table "public"."point_scales" to "authenticated";

grant insert on table "public"."point_scales" to "authenticated";

grant references on table "public"."point_scales" to "authenticated";

grant select on table "public"."point_scales" to "authenticated";

grant trigger on table "public"."point_scales" to "authenticated";

grant truncate on table "public"."point_scales" to "authenticated";

grant update on table "public"."point_scales" to "authenticated";

grant delete on table "public"."point_scales" to "service_role";

grant insert on table "public"."point_scales" to "service_role";

grant references on table "public"."point_scales" to "service_role";

grant select on table "public"."point_scales" to "service_role";

grant trigger on table "public"."point_scales" to "service_role";

grant truncate on table "public"."point_scales" to "service_role";

grant update on table "public"."point_scales" to "service_role";

grant delete on table "public"."settings" to "anon";

grant insert on table "public"."settings" to "anon";

grant references on table "public"."settings" to "anon";

grant select on table "public"."settings" to "anon";

grant trigger on table "public"."settings" to "anon";

grant truncate on table "public"."settings" to "anon";

grant update on table "public"."settings" to "anon";

grant delete on table "public"."settings" to "authenticated";

grant insert on table "public"."settings" to "authenticated";

grant references on table "public"."settings" to "authenticated";

grant select on table "public"."settings" to "authenticated";

grant trigger on table "public"."settings" to "authenticated";

grant truncate on table "public"."settings" to "authenticated";

grant update on table "public"."settings" to "authenticated";

grant delete on table "public"."settings" to "service_role";

grant insert on table "public"."settings" to "service_role";

grant references on table "public"."settings" to "service_role";

grant select on table "public"."settings" to "service_role";

grant trigger on table "public"."settings" to "service_role";

grant truncate on table "public"."settings" to "service_role";

grant update on table "public"."settings" to "service_role";

grant delete on table "public"."users_roles" to "anon";

grant insert on table "public"."users_roles" to "anon";

grant references on table "public"."users_roles" to "anon";

grant select on table "public"."users_roles" to "anon";

grant trigger on table "public"."users_roles" to "anon";

grant truncate on table "public"."users_roles" to "anon";

grant update on table "public"."users_roles" to "anon";

grant delete on table "public"."users_roles" to "authenticated";

grant insert on table "public"."users_roles" to "authenticated";

grant references on table "public"."users_roles" to "authenticated";

grant select on table "public"."users_roles" to "authenticated";

grant trigger on table "public"."users_roles" to "authenticated";

grant truncate on table "public"."users_roles" to "authenticated";

grant update on table "public"."users_roles" to "authenticated";

grant delete on table "public"."users_roles" to "service_role";

grant insert on table "public"."users_roles" to "service_role";

grant references on table "public"."users_roles" to "service_role";

grant select on table "public"."users_roles" to "service_role";

grant trigger on table "public"."users_roles" to "service_role";

grant truncate on table "public"."users_roles" to "service_role";

grant update on table "public"."users_roles" to "service_role";

grant delete on table "public"."users_teams" to "anon";

grant insert on table "public"."users_teams" to "anon";

grant references on table "public"."users_teams" to "anon";

grant select on table "public"."users_teams" to "anon";

grant trigger on table "public"."users_teams" to "anon";

grant truncate on table "public"."users_teams" to "anon";

grant update on table "public"."users_teams" to "anon";

grant delete on table "public"."users_teams" to "authenticated";

grant insert on table "public"."users_teams" to "authenticated";

grant references on table "public"."users_teams" to "authenticated";

grant select on table "public"."users_teams" to "authenticated";

grant trigger on table "public"."users_teams" to "authenticated";

grant truncate on table "public"."users_teams" to "authenticated";

grant update on table "public"."users_teams" to "authenticated";

grant delete on table "public"."users_teams" to "service_role";

grant insert on table "public"."users_teams" to "service_role";

grant references on table "public"."users_teams" to "service_role";

grant select on table "public"."users_teams" to "service_role";

grant trigger on table "public"."users_teams" to "service_role";

grant truncate on table "public"."users_teams" to "service_role";

grant update on table "public"."users_teams" to "service_role";

create policy "Enable read access for all users"
on "public"."estimations"
as permissive
for select
to public
using (true);


create policy "Enable updates for authenticated users only"
on "public"."estimations"
as permissive
for update
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id))
with check (true);


create policy "Enable read access for all users"
on "public"."point_scales"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."roles"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."roles"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."settings"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."users_roles"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."users_roles"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."users_teams"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."users_teams"
as permissive
for select
to public
using (true);


CREATE TRIGGER user_added_to_team AFTER INSERT OR UPDATE ON public.users_teams FOR EACH ROW EXECUTE FUNCTION update_member_count();


